require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/autors", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Autor. As you add validations to Autor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { nome: "John Doe", cpf: "12463278722" }
  }

  

  let(:invalid_attributes) {
    { nome: "", cpf: "123456789" }
  }

  describe "GET /index" do
    it "renders a successful response" do
      Autor.create! valid_attributes
      get autors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      autor = Autor.create! valid_attributes
      get autor_url(autor)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_autor_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      autor = Autor.create! valid_attributes
      get edit_autor_url(autor)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Autor" do
        expect {
          post autors_url, params: { autor: valid_attributes }
        }.to change(Autor, :count).by(1)
      end

      it "redirects to the created autor" do
        post autors_url, params: { autor: valid_attributes }
        expect(response).to redirect_to(autor_url(Autor.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Autor" do
        expect {
          post autors_url, params: { autor: invalid_attributes }
        }.to change(Autor, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post autors_url, params: { autor: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested autor" do
        autor = Autor.create! valid_attributes
        patch autor_url(autor), params: { autor: new_attributes }
        autor.reload

        expect(autor.nome).to eq(new_attributes[:nome])
        expect(autor.cpf).to eq(new_attributes[:cpf])
      end

      it "redirects to the autor" do
        autor = Autor.create! valid_attributes
        patch autor_url(autor), params: { autor: new_attributes }
        autor.reload
        expect(response).to redirect_to(autor_url(autor))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        autor = Autor.create! valid_attributes
        patch autor_url(autor), params: { autor: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested autor" do
      autor = Autor.create! valid_attributes
      expect {
        delete autor_url(autor)
      }.to change(Autor, :count).by(-1)
    end

    it "redirects to the autors list" do
      autor = Autor.create! valid_attributes
      delete autor_url(autor)
      expect(response).to redirect_to(autors_url)
    end
  end
end
